substitutions:
  _REGION: "us-central1"
  _REPOSITORY: "frontimage"
  _IMAGE: "frontend"
  _SERVICE: "frontend"

  _VITE_API_URL: "https://backendn-887266426178.us-central1.run.app"

  _VITE_FIREBASE_AUTH_DOMAIN: "conectasalud-eq3.firebaseapp.com"
  _VITE_FIREBASE_PROJECT_ID: "conectasalud-eq3"
  _VITE_FIREBASE_STORAGE_BUCKET: "conectasalud-eq3.firebasestorage.app"
  _VITE_FIREBASE_MESSAGING_SENDER_ID: "884572026666"
  _VITE_FIREBASE_APP_ID: "1:884572026666:web:282d590022bcdcc6b4d053"

options:
  logging: CLOUD_LOGGING_ONLY

steps:

  - id: build-and-push
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail

        VERSION="${BUILD_ID}"

        IMAGE_BASE="${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}"

        docker build \
          -t "$$IMAGE_BASE:$$VERSION" \
          -t "$$IMAGE_BASE:latest" \
          --build-arg "VITE_API_URL=${_VITE_API_URL}" \
          --build-arg "VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}" \
          --build-arg "VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}" \
          --build-arg "VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}" \
          --build-arg "VITE_FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET}" \
          --build-arg "VITE_FIREBASE_MESSAGING_SENDER_ID=${_VITE_FIREBASE_MESSAGING_SENDER_ID}" \
          --build-arg "VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}" \
          .

        docker push "$$IMAGE_BASE:$$VERSION"
        docker push "$$IMAGE_BASE:latest"

  - id: deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
          - -c
          - |
            set -euo pipefail

            VERSION="${BUILD_ID}"

            IMAGE="${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:$$VERSION"

            gcloud run deploy "${_SERVICE}" \
              --image "$$IMAGE" \
              --region "${_REGION}" \
              --platform managed \
              --allow-unauthenticated \
              --port 8080 \
              --quiet

    timeout: 1800s
