sonar.projectKey=Conecta-Salud_Front-end
sonar.organization=conecta-salud
sonar.host.url=https://sonarcloud.io

sonar.sources=src,index.html
sonar.exclusions=node_modules/**,dist/**,coverage/**,.storybook/**,src/**/*.stories.tsx

sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.typescript.tsconfigPath=tsconfig.json
